### ISSUE TITLE
Updating WorkFeature WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [Rentlau/WorkFeature-WB#3]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by Rentlau** [comment]
I use Freecad daily but it seems only QT5 is used inside not py3 :
OS: Ubuntu 18.04.1 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15611 (Git)
Build type: Release
Branch: master
Hash: 64a94ae0f7c60fc981086fe157150a9c0dca29c6
Python version: 2.7.15rc1
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/France (fr_FR)
How I can test on py3 ?

**Comment by luzpaz** [comment]
Test it by running the appimage or soon the latest PPA but you need Ubuntu 18.04 i believe (not for the appimage though)

**Comment by Rentlau** [comment]
I download:
**FreeCAD_0.18.15650.glibc2.17-x86_64.AppImage**
but no python 3
OS: Ubuntu 18.04.1 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15650 (Git) AppImage
Build type: Release
Branch: master
Hash: c9b4f4ba6779c9ccddb69fba57eee1b5acfd4083
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/France (fr_FR)
Then I download :
**FreeCAD_0.18.15671_Conda_Py3Qt5_glibc2.12-x86_64.AppImage**
but i have an error message:
<pre>./FreeCAD_0.18.15671_Conda_Py3Qt5_glibc2.12-x86_64.AppImage
/tmp/.mount_FreeCA4mJ2VX
FreeCAD 0.18, Libs: 0.18R15671 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Gtk-<font color="#8AE234"><b>Message</b></font>: <font color="#3465A4">06:31:47.140</font>: Failed to load module &quot;canberra-gtk-module&quot;
<font color="#EF2929"><b>During initialization the error /tmp/.mount_FreeCA4mJ2VX/usr/bin/../lib/libQt5Core.so.5: version `Qt_5.12&apos; not found (required by /home/laurent/.local/lib/python3.6/site-packages/PySide2/QtCore.abi3.so) occurred in /tmp/.mount_FreeCA4mJ2VX/usr/Mod/Arch/InitGui.py</b></font>
<font color="#EF2929"><b>Please look into the log file for further information</b></font>
<font color="#EF2929"><b>During initialization the error /tmp/.mount_FreeCA4mJ2VX/usr/bin/../lib/libQt5Core.so.5: version `Qt_5.12&apos; not found (required by /home/laurent/.local/lib/python3.6/site-packages/PySide2/QtCore.abi3.so) occurred in /tmp/.mount_FreeCA4mJ2VX/usr/Mod/Draft/InitGui.py</b></font>
<font color="#EF2929"><b>Please look into the log file for further information</b></font>
<font color="#EF2929"><b>During initialization the error /tmp/.mount_FreeCA4mJ2VX/usr/bin/../lib/libQt5Core.so.5: version `Qt_5.12&apos; not found (required by /home/laurent/.local/lib/python3.6/site-packages/PySide2/QtCore.abi3.so) occurred in /tmp/.mount_FreeCA4mJ2VX/usr/Mod/Tux/InitGui.py</b></font>
<font color="#EF2929"><b>Please look into the log file for further information</b></font>
<font color="#EF2929"><b>During initialization the error invalid syntax (&lt;string&gt;, line 63) occurred in /home/laurent/.FreeCAD/Mod/FreeCAD_WF_Parametric/InitGui.py</b></font>
<font color="#EF2929"><b>Please look into the log file for further information</b></font>
<font color="#EF2929"><b>During initialization the error /tmp/.mount_FreeCA4mJ2VX/usr/bin/../lib/libQt5Core.so.5: version `Qt_5.12&apos; not found (required by /home/laurent/.local/lib/python3.6/site-packages/PySide2/QtCore.abi3.so) occurred in freecad.pip</b></font>
<font color="#EF2929"><b>--------------------------------------------------------------------------------</b></font>
<font color="#EF2929"><b>Traceback (most recent call last):</b></font>
<font color="#EF2929"><b>  File &quot;&lt;string&gt;&quot;, line 145, in InitApplications</b></font>
<font color="#EF2929"><b>  File &quot;/tmp/.mount_FreeCA4mJ2VX/usr/lib/python3.6/importlib/__init__.py&quot;, line 126, in import_module</b></font>
<font color="#EF2929"><b>    return _bootstrap._gcd_import(name[level:], package, level)</b></font>
<font color="#EF2929"><b>  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 994, in _gcd_import</b></font>
<font color="#EF2929"><b>  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 971, in _find_and_load</b></font>
<font color="#EF2929"><b>  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 955, in _find_and_load_unlocked</b></font>
<font color="#EF2929"><b>  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 665, in _load_unlocked</b></font>
<font color="#EF2929"><b>  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 678, in exec_module</b></font>
<font color="#EF2929"><b>  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed</b></font>
<font color="#EF2929"><b>  File &quot;/tmp/.mount_FreeCA4mJ2VX/usr/lib/python3.6/site-packages/freecad/pip/init_gui.py&quot;, line 2, in &lt;module&gt;</b></font>
<font color="#EF2929"><b>    from PySide import QtCore, QtGui</b></font>
<font color="#EF2929"><b>  File &quot;/tmp/.mount_FreeCA4mJ2VX/usr/Ext/PySide/QtCore.py&quot;, line 1, in &lt;module&gt;</b></font>
<font color="#EF2929"><b>    from PySide2.QtCore import *</b></font>
<font color="#EF2929"><b>ImportError: /tmp/.mount_FreeCA4mJ2VX/usr/bin/../lib/libQt5Core.so.5: version `Qt_5.12&apos; not found (required by /home/laurent/.local/lib/python3.6/site-packages/PySide2/QtCore.abi3.so)</b></font>
<font color="#EF2929"><b>--------------------------------------------------------------------------------</b></font>
<font color="#FCE94F"><b>Cannot find icon: Draft_Trimex</b></font>
</pre>

any help will be useful 
Merci beaucoup

**Comment by luzpaz** [comment]
@Rentlau please report this on the [AppImage forum thread](https://forum.freecadweb.org/viewtopic.php?t=15525)

**Comment by Rentlau** [comment]
using branch : release2019_01
I have no more error with **FreeCAD_0.18.15671_Conda_Py3Qt5_glibc2.12-x86_64.AppImage**
but need more tests for sure

**Comment by luzpaz** [comment]
@Rentlau has released a py3/qt5 compatible version per: https://forum.freecadweb.org/viewtopic.php?f=9&t=27195&start=40#p305483

Closing this ticket.
