### ISSUE TITLE
Invalid syntax initialization error

### ISSUE THREAD

**Issue by silopolis** [Rentlau/WorkFeature-WB#4]
Hi,

When starting Freecad (FreeCAD_0.18.15150_Conda_Py3Qt5_glibc2.12-x86_64.AppImage) I get the following error:

``During initialization the error invalid syntax (<string>, line 58) occurred in /home/tarax/.FreeCAD/Mod/workfeature/InitGui.py
``

**Comment by Rentlau** [comment]
Ok not yet compatible with Py3
I am working on it

**Comment by Rentlau** [comment]
using branch : release2019_01
I have no more error with FreeCAD_0.18.15671_Conda_Py3Qt5_glibc2.12-x86_64.AppImage
could you test ?
Thank you for your feed back

**Comment by Rentlau** [comment]
done and tested with qt5 and py3
