### ISSUE TITLE
Create WB svg icon to show up in the Addon Manager UI

### ISSUE THREAD

**Issue by luzpaz** [Rentlau/WorkFeature-WB#9]
With the latest revision to the Addon Manager, we're bundling all the workbenches/addons icons in to https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/AddonManager/Resources/icons and updating the [.qrc](https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/Resources/AddonManager.qrc) file. Please provide an .svg for this workbench. Thanks!

**Comment by Rentlau** [comment]
You can get the icon in /WorkFeature-WB/Resources/Icons/WF_wf.svg
Thank you

**Comment by luzpaz** [comment]
Thanks. FYI, you're using an older version of inkscape that still uses the old 90dpi instead of the new 96dpi standard. when I open the svg in inkscape it asks me to migrate to the newer standard. You may want to upgrade. Cheers.
